package cc.ccwu.signalfeed

internal val englishStrings = """
首页=Home
数据=Explore
设置=Settings
全部=All
国内=China
全球=World
玩机=Devices
其他=Other
主题=Topic
为你推荐=For you
正在关注=Following
‹ 返回=‹ Back
‹ 返回设置=‹ Settings
返回信息流=Back to feed
返回消息详情=Back to post
清除筛选=Clear filters
仅显示 Breaking=Breaking only
账号：{name}=Account: {name}
刷新信息流=Refresh feed
刷新当前数据=Refresh data
刷新=Refresh
重试=Retry
正在获取消息…=Fetching posts…
还没有消息=No posts yet
关注账号后，这里会按时间显示动态=Follow accounts to see their posts in time order
在设置中导入信息源订阅文件=Import a subscription in Settings
添加信息源=Add subscriptions
阅读详情=Read post
关注账号=Follow account
取消关注=Unfollow
屏蔽此账号=Mute account
分享消息=Share post
分享=Share
消息详情=Post
赛事详情=Race updates
收起详情 ↑=Collapse ↑
展开详情 ↓=Expand ↓
原始来源=Sources
打开原文 ↗=Open original ↗
打开原文=Open original
查看来源 ↗=View source ↗
官方=Official
高可信=High confidence
未确认=Unconfirmed
单一来源=Single source
来源待核实=Source unverified
演示=Demo
知道了=Got it
这是该媒体的独立报道，不代表已由其他媒体核实。原始链接保留在消息详情中。=This is a single outlet's report. It has not been independently corroborated. The original link is available in the post.
内容来自对应机构官方来源。可在消息详情查看原始链接。=Published by the organization's official source. The original link is available in the post.
来自已识别的公开媒体或已核对原始发言；不代表多家媒体独立证实。=From an identified outlet or a checked original statement. This does not mean independent corroboration by multiple outlets.
尚未完成原始来源核验，请以来源说明为准。=The original source has not been verified. Please review the source information.
这是演示数据，不是真实新闻。=This is demo data, not a real report.
可在消息详情查看来源及完整说明。=Open the post to review its sources and full details.
赛事合集=Race collection
查看全部详情 →=Read all updates →
{count} 条 BREAKING={count} breaking updates
{count} 条消息 · 按发布时间排序={count} updates, sorted by time
{count} 条消息 · {names}={count} updates from {names}
阅读详情  →  ·  {count} 个来源=Read post →  {count} sources
第 {round} 站 · F1=Round {round}, F1
F1 赛事动态 · {time}=F1 updates  {time}
刚刚=Just now
自动翻译=Auto translation
自动将消息和内容翻译为界面语言，随时可查看原文=Translate posts into your interface language, with the original always available
正在翻译…=Translating…
机器翻译=Machine translation
查看原文=Show original
查看译文=Show translation
翻译=Translate
正在准备语言包…=Preparing language model…
翻译暂不可用，显示原文=Translation unavailable, showing original
译文仅供参考，可查看原文核对=Machine translation. Check the original when accuracy matters.
语言与外观=Language & appearance
中英文、深色模式和阅读效果=Language, dark mode and reading effects
应用语言=App language
翻译目标跟随应用语言=Translation follows your app language
通过主题包导入更多语言=Import more languages in a theme pack
外观=Appearance
跟随系统=System
浅色=Light
深色=Dark
顶栏背景模糊=Blur header background
保持文字清晰，Android 12 及以上生效=Keeps text sharp, available on Android 12 and later
滚动隐藏顶栏=Hide header on scroll
上滑收起，下滑恢复=Hide when scrolling up, reveal when scrolling down
订阅=Subscriptions
内容筛选=Content filters
主题包=Theme packs
手机 Mod=Phone mods
管理来源、账号与数据栏目=Manage sources, accounts and data panels
屏蔽、保留和 Breaking 通知规则=Mute, allow and breaking notification rules
配色、深浅色和语言字典=Colors, light and dark palettes, language dictionaries
直接在手机安装、停用与卸载=Install, disable and uninstall on your phone
信息源订阅=Source subscriptions
筛选规则=Filter rules
Breaking 规则=Breaking rules
数据栏目=Data panels
主题美化=Themes
Mod 管理=Mod manager
账号与关注=Accounts & following
主题偏好=Topic preferences
阅读与打开方式=Reading & links
功能与回退=Features & rollback
订阅后管理关注和屏蔽=Manage following and muting after subscribing
调整已订阅主题权重=Adjust your topic weights
原文和浏览器设置=Original links and browser settings
恢复之前的交互行为=Restore previous interactions
关注=Follow
加入 Following=Include in Following
屏蔽=Mute
从信息流隐藏=Hide from feed
从信息流和通知中隐藏=Hide from feed and notifications
推荐权重 {weight}=Recommendation weight {weight}
权重 {weight}=Weight {weight}
X 消息直接查看原文=Open X posts directly
跳过详情，使用原来的来源打开方式=Skip the post detail and use the original link viewer
正文整理=Clean post text
关闭后恢复来源原始文本与标签=Turn off to show source metadata and original tags
消息翻译=Post translation
关闭后只显示原文=Turn off to show originals only
分类设置页=Grouped settings
关闭后恢复旧版长列表设置页=Turn off to restore the previous settings list
启用规则 Mod=Enable rule mods
关闭后暂停过滤规则包，不影响已编译的代码 Mod=Turn off to pause rule mods
文件订阅=File subscriptions
关闭后暂停文件订阅并隐藏其帖子，保留订阅及缓存=Pause subscriptions and hide their posts while retaining cached data
加载手机模块=Load phone mods
关闭后退出并重开恢复原版运行逻辑，保留模块包=Turn off and restart to restore the original behavior while retaining installed mods
过滤规则包入口=Rule mod manager
关闭后隐藏关键词过滤规则包管理=Turn off to hide the rule mod manager
新版模型榜=Model charts
关闭后恢复配置列表，显示全部思考强度=Turn off to list every configuration
标签与头像交互=Interactive labels and avatars
关闭后恢复旧版静态标签=Turn off to restore static labels
网页使用默认浏览器=Open links in default browser
关闭后恢复浏览器内嵌页；X 始终使用旧版来源打开方式=Turn off to use browser tabs inside the app; X retains its original viewer
导入文件=Import file
正在识别文件…=Identifying file…
仅需四类文件：主题包、订阅、内容筛选、手机 Mod=Four import types: themes, subscriptions, content filters and phone mods
识别为：{type}=Detected: {type}
{name}\n{detail}\n\n确认安装到对应栏目？={name}\n{detail}\n\nInstall this file?
确认安装=Install
取消=Cancel
安装失败=Installation failed
无法识别文件=Cannot identify file
已添加 {name}=Added {name}
已安装 {name}=Installed {name}
已安装 {name}，重启应用后生效=Installed {name}, restart to apply
移除=Remove
移除后立即停用，原有帖子与缓存保留。=Removal disables the configuration immediately. Cached posts are retained.
已安装 {count} 项。请在设置首页使用统一导入入口。={count} installed. Import files from the Settings home page.
尚未导入=Nothing imported yet
聚合服务=Feed services
聚合服务账号=Service accounts
导出=Export
刷新订阅=Refresh subscriptions
已导出订阅=Subscriptions exported
尚未添加文件订阅=No subscriptions yet
删除订阅=Remove subscription
RSS / Atom 订阅可通过设置首页导入 JSON 或 OPML。重复地址自动合并，停用或删除后隐藏缓存内容。=Import RSS or Atom subscriptions from Settings using JSON or OPML. Duplicate URLs are merged; disabling or removing a source hides its cached posts.
手机模块=Phone modules
安装入口位于设置首页的「导入文件」。=Use Import file on the Settings home page to install.
尚未安装手机模块=No phone modules installed
卸载模块=Uninstall module
卸载=Uninstall
已保存，退出后重新打开生效=Saved. Restart the app to apply.
模块文件已移除，退出后清除内存中的模块代码=Module files removed. Restart to unload the code from memory.
退出应用，重新打开使变更生效=Exit and reopen to apply changes
支持补充屏蔽关键词和账号。请从设置首页的统一入口导入 ZIP。=Add keyword and account filters by importing a ZIP from Settings.
ZIP 规则包=Rule ZIPs
尚未安装规则包=No rule packs installed
已卸载 {name}，消息恢复显示=Uninstalled {name}, posts are visible again
版本 {version}  关键词 {words} 条  账号 {accounts} 个=Version {version}, {words} keywords, {accounts} accounts
版本 {version}=Version {version}
还没有数据栏目=No data panels yet
在设置中导入订阅包，可包含赛历、榜单或自定义内容=Import a subscription pack with calendars, rankings or custom content
{count} 个栏目={count} panels
更新：{time}=Updated: {time}
赛程、积分与模型表现=Schedules, points and model performance
赛历=Calendar
积分=Standings
模型榜=Models
暂时没有数据=No data yet
连接网络后刷新，已有数据会保留在本机。=Connect to the network and refresh. Existing data is cached locally.
时间按手机所在时区显示=Times use your device's time zone
下一场=Next race
最近一场=Latest race
已开赛=Started
正赛=Race
排位赛=Qualifying
冲刺赛=Sprint
冲刺排位=Sprint qualifying
一练=FP1
二练=FP2
三练=FP3
最近赛果=Latest results
车手=Drivers
车队=Teams
车手积分=Driver standings
车队积分=Constructor standings
逐站累计积分=Points by round
每站赛后积分 · 包含冲刺赛计分 · 缺失数据不连线=Points after each round, including sprints. Missing data is not connected.
历史积分尚未同步，请稍后刷新。=Historical points are not synced yet. Try refreshing later.
选择{kind}（{count}/{total}）=Select {kind} ({count}/{total})
已隐藏全部{kind}，点击上方选择即可显示。=All {kind} are hidden. Select some above to display them.
显示哪些{kind}=Choose {kind}
全选=Select all
清空=Clear
完成=Done
横轴：比赛站次 · 可左右滑动 · 点击图例隐藏=Horizontal axis: rounds. Swipe sideways; tap a legend to hide it.
条形长度表示积分，使用相同刻度=Bar lengths show points on the same scale
综合=Overall
速度=Speed
价格=Price
编程=Coding
数学=Math
智能体=Agentic
多语言=Multilingual
首字延迟=First token latency
输入价格=Input price
输出价格=Output price
暂无可用模型指标，请刷新。=No model metrics available. Please refresh.
每个模型一条 · 点击查看雷达图与其他配置=One entry per model. Tap for the radar chart and configurations.
默认配置=Default configuration
默认=Default
未提供=Not provided
选择配置=Select configuration
原始得分 / 与均值差异 / 排名=Score / difference from mean / rank
来源未提供，未参与对比=Not provided by source, excluded from comparison
关闭=Close
可用维度不足 3 项，暂不绘制雷达图。=At least three metrics are needed for a radar chart.
得分对比=Score comparison
排名对比=Rank comparison
排名换算为百分位：越外侧排名越靠前；并列同名次。=Ranks are shown as percentiles. Farther out is better; ties share a rank.
各维度与当前榜单均值对比。=Each metric is compared against the current cohort mean.
旧版配置列表=All configurations
原始文件=Original document
放大=Zoom in
第 {page} / {total} 页=Page {page} of {total}
此页无法显示，打开原文=Cannot render page, open original
文档暂时无法加载，请检查网络后重试=Cannot load document. Check your network and try again.
重新加载=Reload
无法连接信息源。请检查手机网络或代理；有缓存时会继续显示。=Cannot reach sources. Check your network or VPN. Cached posts remain available.
F1 更新失败。请检查手机网络或代理。=F1 update failed. Check your network or VPN.
AI 更新失败。请检查手机网络或代理。=Model update failed. Check your network or VPN.
数据栏目随订阅包添加，也可保留旧版数据文件=Data panels come with subscription packs; older files remain supported
内容筛选包同时管理屏蔽与 Breaking，可导入多份=Import multiple packs to manage muting and breaking rules together
没有配置时显示原始信息流，通知保持关闭=With no rules, show the original feed and leave notifications off
仅在有 Breaking 规则时启用通知=Notifications require breaking rules
语言不支持自动翻译时保留原文=Unsupported translation languages retain original content
版本 {version} · 入口 {entry}。安装后重启应用生效=Version {version}, entry {entry}. Restart after installation.
主题：{topic}=Topic: {topic}
未分类=Uncategorized
{count} 个账号 · {url}={count} accounts  {url}
{count} 条屏蔽或保留规则，{breaking} 条 Breaking 规则={count} mute or allow rules, {breaking} breaking rules
SignalFeed\n导入内容与设置均保存在本机=SignalFeed\nImported content and settings are stored on your device
正在处理=Processing
恢复模式：本次未加载模块=Recovery mode: modules were not loaded
已停用上次异常的模块=Disabled the module that failed last time
模块恢复\n此入口不加载任何模块。停用后保留订阅和文章数据。=Module recovery\nThis entry does not load any modules. Subscriptions and articles are retained.
停用全部运行时模块并打开应用=Disable all modules and open app
此 ZIP 类型不能在手机中直接安装。请使用格式 1 或格式 3 的 Mod=This ZIP cannot be installed on a phone. Use a format 1 or format 3 mod.
翻译器已内置，请在语言与外观中设置；无需导入翻译器文件=Translation is built in. Configure it in Language & appearance.
未找到可用浏览器，请安装或设置默认浏览器=No browser found. Install one or set a default browser.
加入=Add
首次翻译会下载语言模型，完成后可离线使用=The first translation downloads language models for offline use
{minutes}分={minutes}m
{hours}时={hours}h
{days}天={days}d
{days}天 {hours}小时={days}d {hours}h
第 {round} 站=Round {round}
{kind} · 第 {round} 站={kind}, round {round}
{unit} · {variants} 种配置 · 多维对比 →={unit}, {variants} configurations, compare metrics →
{label} · 前 {count} · {unit}={label}, top {count}, {unit}
蓝色：当前配置 · 灰色：榜单均值\n各轴按当前比较范围缩放，越外侧越优；价格和延迟反向。雷达半径不是原始分数。=Blue: selected configuration. Gray: cohort mean.\nAxes are scaled to the current cohort. Farther out is better; price and latency are reversed. Radius is not the raw score.
导入预编译 DEX 的 ZIP 模块，可扩展页面、信息流、网络和应用逻辑。安装、停用、卸载后退出并重新打开生效，无需电脑重新打包 App。=Import a ZIP with precompiled DEX to customize pages, feeds and network behavior. Restart after installing, disabling or uninstalling. No app rebuild is needed.
无法正常启动时，使用桌面的 SignalFeed 恢复入口。旧源码补丁仍需电脑构建，手机模块不能替换系统权限声明。=If startup fails, use SignalFeed Recovery from your launcher. Phone modules cannot replace the system permission declaration.
格式：ZIP 根目录只放 mod.json\n必填：formatVersion（1）、id、name、version\n可选：hideKeywords、hideAccounts（字符串数组）\n同一 id 再次导入会替换旧规则=ZIP root: mod.json only\nRequired: formatVersion (1), id, name, version\nOptional: hideKeywords, hideAccounts (string arrays)\nReimporting the same id replaces its rules
以下为关键词规则包（格式 1），可立即启停；代码和页面扩展请使用上方手机模块。=Rule packs (format 1) can be enabled immediately. Use phone modules above for executable code and page extensions.
正在显示原文=Showing original
保留原文=Keep original
{name} 已应用={name} applied
已导入 {name}=Imported {name}
{count} 个订阅={count} subscriptions
{services} 个服务，{feeds} 个 RSS，{panels} 个数据栏目={services} services, {feeds} RSS feeds, {panels} data panels
版本 {version} · 屏蔽关键词 {words} 条、账号 {accounts} 个=Version {version}, {words} muted keywords, {accounts} accounts
此页用于回退旧版交互。导入内容仍可从上方入口管理。=This page restores the old layout. Imported content is still available above.
关键词规则包在内容筛选中管理=Manage keyword rule packs in Content filters
跳过消息详情，使用旧版信息来源的浏览器打开方式；关闭可回退=Skip the post detail and use the original source viewer. Turn off to restore details.
Mod 管理：导入 ZIP=Manage mods
主题权重=Topic weights
最多 100 个订阅=At most 100 subscriptions
最多导入 100 份来源文件=At most 100 service configurations
配置格式版本应为 1=Configuration formatVersion must be 1
配置 id 无效=Invalid configuration id
账号标识无效=Invalid account id
来源标识无效=Invalid source id
聚合服务文件须列出订阅账号=The service file must list subscribed accounts
同一文件中的账号不能重复=Account ids in a file must be unique
不同服务使用了相同账号标识，请调整来源文件=Different services use the same account id. Update the subscription file.
筛选规则至少需要一个条件=Each filter rule needs at least one condition
Breaking 规则至少需要一个条件=Each breaking rule needs at least one condition
主题长度应为 1 至 32 个字符=Topic names must contain 1 to 32 characters
订阅需要 HTTPS 地址=Subscriptions require HTTPS URLs
订阅地址无效=Invalid subscription URL
请输入有效 HTTPS 地址=Enter a valid HTTPS URL
文件中没有 RSS 订阅=No RSS subscriptions in this file
OPML 中没有 RSS 订阅=No RSS subscriptions in this OPML file
订阅包没有内容=The subscription pack is empty
语言标识无效或重复=Invalid or duplicate language code
语言字典占位符不一致=Language placeholders do not match
语言字典键需要固定文案=Language keys need fixed text
文件超过大小限制=File exceeds the size limit
无法识别文件类型，请检查配置字段=Cannot identify the file type. Check its fields.
ZIP 中没有根目录 mod.json=ZIP root must contain mod.json
Mod 清单过大=Mod manifest is too large
ZIP 文件过多=Too many files in ZIP
名称或版本长度不正确=Invalid name or version length
不支持此 Mod 格式版本=Unsupported mod formatVersion
每类规则最多 200 条=At most 200 entries per rule type
规则包只允许包含根目录 mod.json=Rule ZIPs can only contain mod.json at the root
规则包解压内容不得超过 256 KB=Extracted rule ZIPs must not exceed 256 KB
缺少 classes.dex=classes.dex is missing
缺少 mod.json=mod.json is missing
需要格式 3、API 1 手机模块=Phone modules require format 3 and API 1
只支持 mod.json、classes.dex、assets 和 lib=Only mod.json, classes.dex, assets and lib are supported
路径无效=Invalid path
压缩包路径无效=Invalid ZIP path
重复文件或文件过多=Duplicate files or too many files
模块超过 32 MB=Module exceeds 32 MB
未找到数据数组=Data array not found
刷新失败，显示已导入内容：{reason}=Refresh failed, showing imported content: {reason}
{key} 须为 #RRGGBB={key} must be #RRGGBB
已开始=Started
待举行=Upcoming
{time} · {state}={time}, {state}
{count} 分={count} pts
{source} · 更新于 {time}\n已显示本次同步的数据={source}, updated {time}\nShowing the latest synced data
代表配置取综合分最高项；当前维度{direction}。比较范围为本次同步的 {count} 个模型。=The representative uses the highest overall score. {direction}. Comparing {count} synced models.
越低越好=Lower is better
越高越好=Higher is better
{source} · 综合指数 v{version}\n更新：{time}\n已显示本次同步的数据；免费来源未提供的指标不参与排名。={source}, index v{version}\nUpdated: {time}\nOnly provided metrics participate in rankings.
{label} · {unit} · 越低越好={label}, {unit}, lower is better
{label} · {unit}={label}, {unit}
{value}  ·  均值 {mean}  ·  差值 {difference}  ·  #{rank}/{count}={value}, mean {mean}, difference {difference}, #{rank}/{count}
{label} · {time}={label}, {time}
""".trimIndent().lines().filter { it.contains('=') }.associate {
    it.substringBefore('=').replace("\\n", "\n") to it.substringAfter('=').replace("\\n", "\n")
}
